repos:
  # General hooks that apply to all files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # Python specific hooks - using just commands for NixOS compatibility
  - repo: local
    hooks:
      - id: format
        name: Format Python code
        entry: just format
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: lint
        name: Lint Python code
        entry: just lint
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true

# Configuration
default_stages: [pre-commit]
fail_fast: true
